export interface Spell {
  name: string;
  level: number;
  school: string;
  range: string;
  duration: string;
  area_of_effect: string;
  components: string;
  casting_time: string;
  saving_throw: string;
  description: string;
  class: 'wizard' | 'priest';
}

export const arcaneSpells: Spell[] = [
  // Level 1
  {
    name: "Míssil Mágico",
    level: 1,
    school: "Evocação",
    range: "137m",
    duration: "Instantânea",
    area_of_effect: "1 criatura",
    components: "V, S",
    casting_time: "1",
    saving_throw: "Nenhum",
    description: "Cria um ou mais mísseis mágicos que atingem um alvo automaticamente. A cada dois níveis, o conjurador ganha um míssil adicional.",
    class: 'wizard',
  },
  {
    name: "Detectar Magia",
    level: 1,
    school: "Adivinhação",
    range: "0",
    duration: "1 turno",
    area_of_effect: "Caminho de 18m",
    components: "V, S",
    casting_time: "1",
    saving_throw: "Nenhum",
    description: "O conjurador pode detectar a presença e a localização de itens ou efeitos mágicos dentro da área de efeito.",
    class: 'wizard',
  },
  {
    name: "Sono",
    level: 1,
    school: "Encantamento/Feitiço",
    range: "27m",
    duration: "5 rodadas/nível",
    area_of_effect: "Raio de 3m",
    components: "V, S, M",
    casting_time: "1",
    saving_throw: "Nenhum",
    description: "Causa um sono mágico em criaturas. Afeta 2d4 Dados de Vida de criaturas.",
    class: 'wizard',
  },
  // Level 2
  {
    name: "Invisibilidade",
    level: 2,
    school: "Ilusão/Fantasma",
    range: "Toque",
    duration: "Especial",
    area_of_effect: "1 criatura",
    components: "V, S, M",
    casting_time: "2",
    saving_throw: "Nenhum",
    description: "O alvo deste feitiço se torna invisível. O feitiço termina quando o alvo ataca qualquer criatura.",
    class: 'wizard',
  },
  {
    name: "Teia",
    level: 2,
    school: "Evocação",
    range: "9m/nível",
    duration: "2 turnos/nível",
    area_of_effect: "Até um cubo de 6m",
    components: "V, S, M",
    casting_time: "2",
    saving_throw: "Nega",
    description: "Cria uma massa de fios fortes e pegajosos. Criaturas presas nela ficam emaranhadas e podem não conseguir se mover.",
    class: 'wizard',
  },
  // Level 3
  {
    name: "Bola de Fogo",
    level: 3,
    school: "Evocação",
    range: "9m + 1m/nível",
    duration: "Instantânea",
    area_of_effect: "Esfera de 6m de raio",
    components: "V, S, M",
    casting_time: "3",
    saving_throw: "Metade",
    description: "Uma explosão de chamas que detona com um rugido baixo e causa 1d6 de dano de fogo por nível do conjurador a todas as criaturas na área.",
    class: 'wizard',
  },
  {
    name: "Relâmpago",
    level: 3,
    school: "Evocação",
    range: "36m + 9m/nível",
    duration: "Instantânea",
    area_of_effect: "Um raio de 1,5m de largura até seu alcance máximo",
    components: "V, S, M",
    casting_time: "3",
    saving_throw: "Metade",
    description: "Um poderoso raio de energia elétrica que causa 1d6 de dano por nível do conjurador.",
    class: 'wizard',
  },
];

export const divineSpells: Spell[] = [
  // Level 1
  {
    name: "Curar Ferimentos Leves",
    level: 1,
    school: "Necromancia",
    range: "Toque",
    duration: "Permanente",
    area_of_effect: "1 criatura",
    components: "V, S",
    casting_time: "5",
    saving_throw: "Nenhum",
    description: "Cura 1d8 pontos de dano em uma criatura tocada. Este feitiço não pode afetar mortos-vivos.",
    class: 'priest',
  },
  {
    name: "Bênção",
    level: 1,
    school: "Conjuração/Invocação",
    range: "45m",
    duration: "6 rodadas",
    area_of_effect: "Cubo de 15m",
    components: "V, S, M",
    casting_time: "1 rodada",
    saving_throw: "Nenhum",
    description: "Aliados na área de efeito ganham um bônus de +1 em suas jogadas de ataque e testes de resistência contra efeitos de medo.",
    class: 'priest',
  },
  {
    name: "Detectar o Mal",
    level: 1,
    school: "Adivinhação",
    range: "0",
    duration: "1 turno",
    area_of_effect: "Caminho de 18m",
    components: "V, S",
    casting_time: "1 rodada",
    saving_throw: "Nenhum",
    description: "O conjurador pode detectar a presença de intenções ou criaturas malignas.",
    class: 'priest',
  },
  // Level 2
  {
    name: "Imobilizar Pessoa",
    level: 2,
    school: "Encantamento/Feitiço",
    range: "110m",
    duration: "1 turno/nível",
    area_of_effect: "1-4 pessoas em um cubo de 6m",
    components: "V, S, M",
    casting_time: "5",
    saving_throw: "Nega",
    description: "Este feitiço faz com que uma ou mais criaturas humanoides fiquem paralisadas e incapazes de agir. Um teste de resistência bem-sucedido nega o efeito.",
    class: 'priest',
  },
  {
    name: "Martelo Espiritual",
    level: 2,
    school: "Evocação",
    range: "27m",
    duration: "3 rodadas/nível",
    area_of_effect: "1 criatura",
    components: "V, S",
    casting_time: "5",
    saving_throw: "Nenhum",
    description: "Cria um martelo mágico que ataca um inimigo designado pelo conjurador. Ele ataca como uma arma mágica e causa 1d4+1 de dano.",
    class: 'priest',
  },
  // Level 3
  {
    name: "Remover Maldição",
    level: 3,
    school: "Abjuração",
    range: "Toque",
    duration: "Permanente",
    area_of_effect: "1 criatura ou objeto",
    components: "V, S",
    casting_time: "1 turno",
    saving_throw: "Nenhum",
    description: "Este feitiço remove uma maldição de uma pessoa ou objeto. Não remove a maldição de um escudo, arma ou armadura amaldiçoados.",
    class: 'priest',
  },
  {
    name: "Curar Doença",
    level: 3,
    school: "Necromancia",
    range: "Toque",
    duration: "Permanente",
    area_of_effect: "1 criatura",
    components: "V, S",
    casting_time: "1 turno",
    saving_throw: "Nenhum",
    description: "Cura o alvo de quaisquer doenças não mágicas. Não afeta doenças mágicas como licantropia.",
    class: 'priest',
  },
];